// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-lua-module.mjs

export const LUA_SCRIPTS: Record<string, string> = {
  'check-stalled': `-- Check for stalled jobs and move them back to waiting or fail them
-- KEYS: namespace, currentTime, gracePeriod, maxStalledCount
-- Returns: array of [jobId, groupId, action] for each stalled job found
--   action: "recovered" or "failed"

local ns = KEYS[1]
local now = tonumber(ARGV[1])
local gracePeriod = tonumber(ARGV[2]) or 0
local maxStalledCount = tonumber(ARGV[3]) or 1

-- Circuit breaker for high concurrency: limit stalled job recovery
local circuitBreakerKey = ns .. ":stalled:circuit"
local lastCheck = redis.call("GET", circuitBreakerKey)
if lastCheck then
  local lastCheckTime = tonumber(lastCheck)
  local circuitBreakerInterval = 2000
  if lastCheckTime and (now - lastCheckTime) < circuitBreakerInterval then
    return {}
  end
end
redis.call("SET", circuitBreakerKey, now, "PX", 3000)

local processingKey = ns .. ":processing"
local groupsKey = ns .. ":groups"

-- Candidates: jobs whose deadlines are past
local candidates = redis.call("ZRANGEBYSCORE", processingKey, 0, now - gracePeriod, "LIMIT", 0, 100)
if not candidates or #candidates == 0 then
  return {}
end

local results = {}

for _, jobId in ipairs(candidates) do
  local jobKey = ns .. ":job:" .. jobId
  local h = redis.call("HMGET", jobKey, "groupId","stalledCount","maxAttempts","attempts","status","finishedOn","score")
  local groupId = h[1]
  local status = h[5]

  -- Self-healing: if job hash is gone (no groupId) the processing entry is
  -- unreachable from any other code path. Just drop it so it stops looking
  -- like an active job forever.
  if not groupId then
    redis.call("ZREM", processingKey, jobId)
    table.insert(results, jobId); table.insert(results, ""); table.insert(results, "orphaned")
  -- Self-healing: if status is no longer "processing" some other path
  -- already handled this job (recovery, completion, manual fix, etc.) but
  -- failed to clear the processing zset entry. Drop it and remove from the
  -- group's active list so the group isn't blocked.
  elseif status ~= "processing" then
    redis.call("ZREM", processingKey, jobId)
    local groupActiveKey = ns .. ":g:" .. groupId .. ":active"
    redis.call("LREM", groupActiveKey, 0, jobId)
    table.insert(results, jobId); table.insert(results, groupId); table.insert(results, "orphaned")
  else
    local stalledCount = tonumber(h[2]) or 0
    local maxAttempts = tonumber(h[3]) or 3
    local finishedOn = tonumber(h[6] or "0")
    stalledCount = stalledCount + 1
    redis.call("HSET", jobKey, "stalledCount", stalledCount)
    -- BullMQ-style: Remove from per-group active list
    local groupActiveKey = ns .. ":g:" .. groupId .. ":active"
    redis.call("LREM", groupActiveKey, 1, jobId)

    if stalledCount >= maxStalledCount and maxStalledCount > 0 then
      redis.call("ZREM", processingKey, jobId)
      local groupKey = ns .. ":g:" .. groupId
      redis.call("ZREM", groupKey, jobId)
      redis.call("HSET", jobKey, "status","failed","finishedOn", now,
                 "failedReason", "Job stalled " .. stalledCount .. " times (max: " .. maxStalledCount .. ")")
      redis.call("ZADD", ns .. ":failed", now, jobId)
      table.insert(results, jobId); table.insert(results, groupId); table.insert(results, "failed")
    else
      local stillInProcessing = redis.call("ZSCORE", processingKey, jobId)
      if stillInProcessing then
        redis.call("ZREM", processingKey, jobId)
        local score = tonumber(h[7])
        if score then
          local groupKey2 = ns .. ":g:" .. groupId
          redis.call("ZADD", groupKey2, score, jobId)
          local head = redis.call("ZRANGE", groupKey2, 0, 0, "WITHSCORES")
          if head and #head >= 2 then
            local headScore = tonumber(head[2])
            redis.call("ZADD", ns .. ":ready", headScore, groupId)
          end
          redis.call("SADD", groupsKey, groupId)
        end
        redis.call("HSET", jobKey, "status", "waiting")
        table.insert(results, jobId); table.insert(results, groupId); table.insert(results, "recovered")
      end
    end
  end
end

return results

`,
  'clean-status': `-- argv: ns, status, graceAtMs, limit
local ns = KEYS[1]
local status = ARGV[1]
local graceAt = tonumber(ARGV[2]) or 0
local limit = tonumber(ARGV[3]) or 1000

local setKey = nil
if status == 'completed' then
  setKey = ns .. ':completed'
elseif status == 'failed' then
  setKey = ns .. ':failed'
elseif status == 'delayed' then
  setKey = ns .. ':delayed'
else
  -- unsupported status for clean
  return 0
end

-- Fetch up to 'limit' job ids with score <= graceAt
local ids = redis.call('ZRANGEBYSCORE', setKey, '-inf', graceAt, 'LIMIT', 0, limit)

local removed = 0
for i = 1, #ids do
  local id = ids[i]
  local jobKey = ns .. ':job:' .. id

  -- Remove from the primary set first to avoid reprocessing
  redis.call('ZREM', setKey, id)

  -- Remove from group and update ready queue for ALL statuses
  -- This prevents poisoned groups when completed/failed jobs are cleaned
  local groupId = redis.call('HGET', jobKey, 'groupId')
  if groupId then
    local gZ = ns .. ':g:' .. groupId
    local readyKey = ns .. ':ready'
    redis.call('ZREM', gZ, id)
    local jobCount = redis.call('ZCARD', gZ)
    if jobCount == 0 then
      redis.call('ZREM', readyKey, groupId)
      -- Clean up empty group
      redis.call('DEL', gZ)
      redis.call('SREM', ns .. ':groups', groupId)
    elseif status == 'delayed' then
      -- Only update ready queue score for delayed jobs
      -- (completed/failed jobs shouldn't affect ready queue)
      local head = redis.call('ZRANGE', gZ, 0, 0, 'WITHSCORES')
      if head and #head >= 2 then
        local headScore = tonumber(head[2])
        redis.call('ZADD', readyKey, headScore, groupId)
      end
    end
  end

  -- Delete job hash and idempotence key
  redis.call('DEL', jobKey)
  redis.call('DEL', ns .. ':unique:' .. id)

  removed = removed + 1
end

return removed


`,
  'cleanup-poisoned-group': `-- argv: ns, groupId, now
local ns = KEYS[1]
local groupId = ARGV[1]
local now = tonumber(ARGV[2])

local readyKey = ns .. ":ready"
local gZ = ns .. ":g:" .. groupId
local lockKey = ns .. ":lock:" .. groupId

-- Check if group has any jobs at all
local jobCount = redis.call("ZCARD", gZ)
if jobCount == 0 then
  redis.call("ZREM", readyKey, groupId)
  return "empty"
end

-- Check if group is currently locked by another worker
local lockValue = redis.call("GET", lockKey)
if lockValue then
  local lockTtl = redis.call("PTTL", lockKey)
  if lockTtl > 0 then
    return "locked"
  end
end

-- Check if all jobs in the group have exceeded max attempts
local jobs = redis.call("ZRANGE", gZ, 0, -1)
local reservableJobs = 0
for i = 1, #jobs do
  local jobId = jobs[i]
  local jobKey = ns .. ":job:" .. jobId
  local attempts = tonumber(redis.call("HGET", jobKey, "attempts"))
  local maxAttempts = tonumber(redis.call("HGET", jobKey, "maxAttempts"))
  if attempts and maxAttempts and attempts < maxAttempts then
    reservableJobs = reservableJobs + 1
  end
end

if reservableJobs == 0 then
  redis.call("ZREM", readyKey, groupId)
  return "poisoned"
end

return "ok"


`,
  'cleanup': `-- argv: ns, nowEpochMs
local ns = KEYS[1]
local now = tonumber(ARGV[1])

local readyKey = ns .. ":ready"
local processingKey = ns .. ":processing"
local cleaned = 0

local expiredJobs = redis.call("ZRANGEBYSCORE", processingKey, 0, now)
for _, jobId in ipairs(expiredJobs) do
  -- CRITICAL: Verify job is STILL in processing to avoid race conditions
  -- If job was completed between our snapshot and now, don't re-add it
  local stillInProcessing = redis.call("ZSCORE", processingKey, jobId)
  
  if stillInProcessing then
    local gid = redis.call("HGET", ns .. ":job:" .. jobId, "groupId")
    local deadlineAt = tonumber(stillInProcessing)
    if gid and deadlineAt and now > deadlineAt then
      local jobKey = ns .. ":job:" .. jobId
      local jobScore = redis.call("HGET", jobKey, "score")
      if jobScore then
        local gZ = ns .. ":g:" .. gid
        -- CRITICAL: Check if job is already in group set before re-adding
        -- This prevents duplicate entries and ensures we only re-add if truly needed
        local alreadyInGroup = redis.call("ZSCORE", gZ, jobId)
        if not alreadyInGroup then
          redis.call("ZADD", gZ, tonumber(jobScore), jobId)
        end
        -- CRITICAL: Reset status from "processing" to "waiting" when re-adding expired job
        -- This prevents jobs from being stuck with "processing" status in the group set
        redis.call("HSET", jobKey, "status", "waiting")
        local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
        if head and #head >= 2 then
          local headScore = tonumber(head[2])
          redis.call("ZADD", readyKey, headScore, gid)
        end
        -- Remove from group active list (BullMQ-style)
        local groupActiveKey = ns .. ":g:" .. gid .. ":active"
        redis.call("LREM", groupActiveKey, 1, jobId)
        redis.call("DEL", ns .. ":lock:" .. gid)
        redis.call("ZREM", processingKey, jobId)
        
        -- No counter operations - use ZCARD for counts
        
        cleaned = cleaned + 1
      end
    end
  end
  -- If not still in processing, it was completed - don't re-add it!
end

return cleaned


`,
  'complete-and-reserve-next-with-metadata': `-- Complete a job with metadata and atomically reserve the next job from the same group
-- argv: ns, completedJobId, groupId, status, timestamp, resultOrError, keepCompleted, keepFailed,
--       processedOn, finishedOn, attempts, maxAttempts, now, vt
local ns = KEYS[1]
local completedJobId = ARGV[1]
local gid = ARGV[2]
local status = ARGV[3]
local timestamp = tonumber(ARGV[4])
local resultOrError = ARGV[5]
local keepCompleted = tonumber(ARGV[6])
local keepFailed = tonumber(ARGV[7])
local processedOn = ARGV[8]
local finishedOn = ARGV[9]
local attempts = ARGV[10]
local maxAttempts = ARGV[11]
local now = tonumber(ARGV[12])
local vt = tonumber(ARGV[13])

-- Part 1: Atomically verify and mark completion (prevent duplicate processing)
local jobKey = ns .. ":job:" .. completedJobId
local processingKey = ns .. ":processing"

-- CRITICAL: Check both status AND processing set membership atomically
-- This prevents race with stalled job recovery
local jobStatus = redis.call("HGET", jobKey, "status")
local stillInProcessing = redis.call("ZSCORE", processingKey, completedJobId)

-- If job is not in "processing" state OR not in processing set, this is late/duplicate
if jobStatus ~= "processing" or not stillInProcessing then
  return nil
end

-- Atomically remove from processing
redis.call("ZREM", processingKey, completedJobId)

-- Part 3: Record job metadata (completed or failed)

if status == "completed" then
  local completedKey = ns .. ":completed"
  
  -- CRITICAL: Always set final status first, even if job will be deleted
  -- This ensures any concurrent reads see "completed", not "completing"
  redis.call("HSET", jobKey, "status", "completed")
  
  if keepCompleted > 0 then
    -- Store full job metadata and add to completed set
    redis.call("HSET", jobKey, 
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts,
      "returnvalue", resultOrError
    )
    redis.call("ZADD", completedKey, timestamp, completedJobId)
    
    -- Trim old entries atomically
    local zcount = redis.call("ZCARD", completedKey)
    local toRemove = zcount - keepCompleted
    if toRemove > 0 then
      local oldIds = redis.call("ZRANGE", completedKey, 0, toRemove - 1)
      if #oldIds > 0 then
        redis.call("ZREMRANGEBYRANK", completedKey, 0, toRemove - 1)
        for i = 1, #oldIds do
          local oldId = oldIds[i]
          redis.call("DEL", ns .. ":job:" .. oldId)
          redis.call("DEL", ns .. ":unique:" .. oldId)
        end
      end
    end
  else
    -- keepCompleted == 0: Delete immediately (status already set above)
    redis.call("DEL", jobKey)
    redis.call("DEL", ns .. ":unique:" .. completedJobId)
  end
  
elseif status == "failed" then
  local failedKey = ns .. ":failed"
  local errorInfo = cjson.decode(resultOrError)
  
  -- CRITICAL: Always set final status first, even if job will be deleted
  redis.call("HSET", jobKey, "status", "failed")
  
  if keepFailed > 0 then
    redis.call("HSET", jobKey,
      "failedReason", errorInfo.message or "Error",
      "failedName", errorInfo.name or "Error",
      "stacktrace", errorInfo.stack or "",
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts
    )
    redis.call("ZADD", failedKey, timestamp, completedJobId)
  else
    -- Delete job (status already set above)
    redis.call("DEL", jobKey)
    redis.call("DEL", ns .. ":unique:" .. completedJobId)
  end
end

-- Part 3: Handle group active list and get next job (BullMQ-style)
local groupActiveKey = ns .. ":g:" .. gid .. ":active"
local activeJobId = redis.call("LINDEX", groupActiveKey, 0)

-- Always clean up this job from active list, even if not at head
-- This prevents stale active lists from race conditions
if activeJobId == completedJobId then
  -- Normal case: this job is at the head of active list
  redis.call("LPOP", groupActiveKey)
else
  -- Race condition: job is not at head (maybe already removed, or wrong job)
  -- Clean it up anyway to prevent stale entries
  redis.call("LREM", groupActiveKey, 1, completedJobId)
  
  -- If active list had a different job or was empty, don't try to reserve next
  -- Return nil to indicate no chaining
  return nil
end

local gZ = ns .. ":g:" .. gid
local zpop = redis.call("ZPOPMIN", gZ, 1)
if not zpop or #zpop == 0 then
  -- Clean up empty group
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount == 0 then
    redis.call("DEL", gZ)
    redis.call("SREM", ns .. ":groups", gid)
    redis.call("ZREM", ns .. ":ready", gid)
  end
  -- No next job
  return nil
end

local nextJobId = zpop[1]
local nextJobKey = ns .. ":job:" .. nextJobId
local job = redis.call("HMGET", nextJobKey, "id","groupId","data","attempts","maxAttempts","seq","timestamp","orderMs","score")
local id, groupId, payload, attempts, maxAttempts, seq, enq, orderMs, score = job[1], job[2], job[3], job[4], job[5], job[6], job[7], job[8], job[9]

-- Validate job data exists (handle corrupted/missing job hash)
if not id or id == false then
  -- Job hash is missing/corrupted, clean up and return completion only
  -- Re-add next job to ready queue if exists
  local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if nextHead and #nextHead >= 2 then
    local nextScore = tonumber(nextHead[2])
    local readyKey = ns .. ":ready"
    redis.call("ZADD", readyKey, nextScore, groupId)
  end
  
  -- Return nil to indicate no next job was reserved
  return nil
end

-- Push next job to active list (chaining)
redis.call("LPUSH", groupActiveKey, id)

local deadline = now + vt

local processingKey = ns .. ":processing"
redis.call("ZADD", processingKey, deadline, id)

-- Mark next job as processing for accurate stalled detection
redis.call("HSET", nextJobKey, "status", "processing")

local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
if nextHead and #nextHead >= 2 then
  local nextScore = tonumber(nextHead[2])
  local readyKey = ns .. ":ready"
  redis.call("ZADD", readyKey, nextScore, groupId)
end

return id .. "||GROUPMQ||" .. groupId .. "||GROUPMQ||" .. payload .. "||GROUPMQ||" .. attempts .. "||GROUPMQ||" .. maxAttempts .. "||GROUPMQ||" .. seq .. "||GROUPMQ||" .. enq .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. score .. "||GROUPMQ||" .. deadline`,
  'complete-with-metadata': `-- Complete a job: unlock group AND record metadata atomically in one call
-- argv: ns, jobId, groupId, status, timestamp, resultOrError, keepCompleted, keepFailed,
--       processedOn, finishedOn, attempts, maxAttempts
local ns = KEYS[1]
local jobId = ARGV[1]
local gid = ARGV[2]
local status = ARGV[3]
local timestamp = tonumber(ARGV[4])
local resultOrError = ARGV[5]
local keepCompleted = tonumber(ARGV[6])
local keepFailed = tonumber(ARGV[7])
local processedOn = ARGV[8]
local finishedOn = ARGV[9]
local attempts = ARGV[10]
local maxAttempts = ARGV[11]

-- Part 1: Atomically verify and mark completion (prevent duplicate processing)
local jobKey = ns .. ":job:" .. jobId
local processingKey = ns .. ":processing"

-- CRITICAL: Check both status AND processing set membership atomically
-- This prevents race with stalled job recovery
local jobStatus = redis.call("HGET", jobKey, "status")
local stillInProcessing = redis.call("ZSCORE", processingKey, jobId)

-- If job is not in "processing" state OR not in processing set, this is late/duplicate
if jobStatus ~= "processing" or not stillInProcessing then
  -- Job was already handled (recovered, failed, or completed by another worker)
  -- Return 0 to indicate this completion was ignored
  return 0
end

-- Atomically remove from processing
redis.call("ZREM", processingKey, jobId)

-- Handle group operations only if groupId is not empty (simple jobs skip this)
if gid and gid ~= "" then
  -- Always remove this job from active list to prevent stale entries
  local groupActiveKey = ns .. ":g:" .. gid .. ":active"
  local activeJobId = redis.call("LINDEX", groupActiveKey, 0)
  local wasActive = (activeJobId == jobId)

  if wasActive then
    -- Normal case: remove from head of active list
    redis.call("LPOP", groupActiveKey)
  else
    -- Race condition: not at head, but still remove to prevent stale entries
    redis.call("LREM", groupActiveKey, 1, jobId)
  end

  -- Check if there are more jobs in this group
  local gZ = ns .. ":g:" .. gid
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount == 0 then
    -- Remove empty group
    redis.call("DEL", gZ)
    redis.call("DEL", groupActiveKey)
    redis.call("SREM", ns .. ":groups", gid)
    redis.call("ZREM", ns .. ":ready", gid)
    redis.call("DEL", ns .. ":buffer:" .. gid)
    redis.call("ZREM", ns .. ":buffering", gid)
  else
    -- Group has more jobs, re-add to ready if not buffering
    local groupBufferKey = ns .. ":buffer:" .. gid
    local isBuffering = redis.call("EXISTS", groupBufferKey)
    
    if isBuffering == 0 then
      local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
      if nextHead and #nextHead >= 2 then
        local nextScore = tonumber(nextHead[2])
        local readyKey = ns .. ":ready"
        redis.call("ZADD", readyKey, nextScore, gid)
      end
    end
  end
end

-- Part 2: Record job metadata (completed or failed)
local jobKey = ns .. ":job:" .. jobId

if status == "completed" then
  local completedKey = ns .. ":completed"
  
  -- CRITICAL: Always set final status first, even if job will be deleted
  -- This ensures any concurrent reads see "completed", not "completing"
  redis.call("HSET", jobKey, "status", "completed")
  
  if keepCompleted > 0 then
    -- Store full job metadata and add to completed set
    redis.call("HSET", jobKey, 
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts,
      "returnvalue", resultOrError
    )
    redis.call("ZADD", completedKey, timestamp, jobId)
    
    -- Trim old entries atomically
    local zcount = redis.call("ZCARD", completedKey)
    local toRemove = zcount - keepCompleted
    if toRemove > 0 then
      local oldIds = redis.call("ZRANGE", completedKey, 0, toRemove - 1)
      if #oldIds > 0 then
        redis.call("ZREMRANGEBYRANK", completedKey, 0, toRemove - 1)
        for i = 1, #oldIds do
          local oldId = oldIds[i]
          redis.call("DEL", ns .. ":job:" .. oldId)
          redis.call("DEL", ns .. ":unique:" .. oldId)
        end
      end
    end
  else
    -- keepCompleted == 0: Delete immediately (status already set above)
    redis.call("DEL", jobKey)
    redis.call("DEL", ns .. ":unique:" .. jobId)
  end
  
elseif status == "failed" then
  local failedKey = ns .. ":failed"
  local errorInfo = cjson.decode(resultOrError)
  
  -- CRITICAL: Always set final status first, even if job will be deleted
  redis.call("HSET", jobKey, "status", "failed")
  
  if keepFailed > 0 then
    redis.call("HSET", jobKey,
      "failedReason", errorInfo.message or "Error",
      "failedName", errorInfo.name or "Error",
      "stacktrace", errorInfo.stack or "",
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts
    )
    redis.call("ZADD", failedKey, timestamp, jobId)
  else
    -- Delete job (status already set above)
    redis.call("DEL", jobKey)
    redis.call("DEL", ns .. ":unique:" .. jobId)
  end
end

return 1

`,
  'complete': `-- Complete a job by removing from processing and unlocking the group
-- Does NOT record job metadata - that's handled separately by record-job-result.lua
-- argv: ns, jobId, groupId
local ns = KEYS[1]
local jobId = ARGV[1]
local gid = ARGV[2]

-- Remove from processing
redis.call("ZREM", ns .. ":processing", jobId)

-- Check if this job holds the lock
local lockKey = ns .. ":lock:" .. gid
local val = redis.call("GET", lockKey)
if val == jobId then
  redis.call("DEL", lockKey)
  
  -- Check if there are more jobs in this group
  local gZ = ns .. ":g:" .. gid
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount == 0 then
    -- Remove empty group zset and from groups tracking set
    redis.call("DEL", gZ)
    redis.call("SREM", ns .. ":groups", gid)
    -- Remove from ready queue
    redis.call("ZREM", ns .. ":ready", gid)
    -- Clean up any buffering state (shouldn't exist but be safe)
    redis.call("DEL", ns .. ":buffer:" .. gid)
    redis.call("ZREM", ns .. ":buffering", gid)
  else
    -- Group has more jobs, re-add to ready set
    -- Note: If the group was buffering, it will be handled by the buffering logic
    -- If it's not buffering, add to ready immediately
    local groupBufferKey = ns .. ":buffer:" .. gid
    local isBuffering = redis.call("EXISTS", groupBufferKey)
    
    if isBuffering == 0 then
      -- Not buffering, add to ready immediately
      local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
      if nextHead and #nextHead >= 2 then
        local nextScore = tonumber(nextHead[2])
        local readyKey = ns .. ":ready"
        redis.call("ZADD", readyKey, nextScore, gid)
      end
    end
    -- If buffering, the scheduler will promote when ready
  end
  
  return 1
end
return 0
`,
  'dead-letter': `-- argv: ns, jobId, groupId
local ns = KEYS[1]
local jobId = ARGV[1]
local groupId = ARGV[2]
local gZ = ns .. ":g:" .. groupId
local readyKey = ns .. ":ready"

-- Remove job from group
redis.call("ZREM", gZ, jobId)

-- Remove from processing if it's there
redis.call("ZREM", ns .. ":processing", jobId)

-- No counter operations - use ZCARD for counts

-- Remove idempotence mapping to allow reuse
redis.call("DEL", ns .. ":unique:" .. jobId)

-- BullMQ-style: Remove from group active list if present
local groupActiveKey = ns .. ":g:" .. groupId .. ":active"
redis.call("LREM", groupActiveKey, 1, jobId)

-- Check if group is now empty or should be removed from ready queue
local jobCount = redis.call("ZCARD", gZ)
if jobCount == 0 then
  -- Group is empty, remove from ready queue and clean up
  redis.call("ZREM", readyKey, groupId)
  redis.call("DEL", gZ)
  redis.call("DEL", groupActiveKey)
  redis.call("SREM", ns .. ":groups", groupId)
else
  -- Group still has jobs, update ready queue with new head
  local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if head and #head >= 2 then
    local headScore = tonumber(head[2])
    redis.call("ZADD", readyKey, headScore, groupId)
  end
end

-- Optionally store in dead letter queue (uncomment if needed)
-- redis.call("LPUSH", ns .. ":dead", jobId)

return 1

`,
  'enqueue-batch': `-- Batch enqueue multiple jobs atomically
-- argv: ns, jobsJson, keepCompleted, clientTimestamp, orderingDelayMs
local ns = KEYS[1]
local jobsJson = ARGV[1]
local keepCompleted = tonumber(ARGV[2]) or 0
local clientTimestamp = tonumber(ARGV[3])
local orderingDelayMs = tonumber(ARGV[4]) or 0

local jobs = cjson.decode(jobsJson)

-- Get Redis server time
local timeResult = redis.call("TIME")
local now = tonumber(timeResult[1]) * 1000 + math.floor(tonumber(timeResult[2]) / 1000)

-- Keys
local stageKey = ns .. ":stage"
local readyKey = ns .. ":ready"
local groupsKey = ns .. ":groups"
local timerKey = ns .. ":stage:timer"

local baseEpoch = 1704067200000
local daysSinceEpoch = math.floor(clientTimestamp / 86400000)
local seqKey = ns .. ":seq:" .. daysSinceEpoch

-- Track groups that need ready queue updates
local groupsToUpdate = {}
local results = {}

-- Process all jobs in batch
for i, job in ipairs(jobs) do
  local jobId = job.jobId
  local groupId = job.groupId
  local data = job.data
  local maxAttempts = tonumber(job.maxAttempts)
  local orderMs = tonumber(job.orderMs) or clientTimestamp
  
  -- Idempotence check
  local uniqueKey = ns .. ":unique:" .. jobId
  local uniqueSet = redis.call("SET", uniqueKey, jobId, "NX")
  
  if uniqueSet then
    -- Generate sequence and score
    local seq = redis.call("INCR", seqKey)
    local relativeMs = orderMs - baseEpoch
    local score = relativeMs * 1000 + seq
    
    -- Create job hash
    local jobKey = ns .. ":job:" .. jobId
    redis.call("HMSET", jobKey,
      "id", jobId,
      "groupId", groupId,
      "data", data,
      "attempts", "0",
      "maxAttempts", tostring(maxAttempts),
      "seq", tostring(seq),
      "timestamp", tostring(clientTimestamp),
      "orderMs", tostring(orderMs),
      "score", tostring(score)
    )
    
    -- Add to groups set
    redis.call("SADD", groupsKey, groupId)
    
    -- Add to group sorted set
    local gZ = ns .. ":g:" .. groupId
    redis.call("ZADD", gZ, score, jobId)
    
    -- Determine job placement
    local jobStatus = "waiting"
    
    if orderMs and orderingDelayMs > 0 then
      -- Staged job (ordering)
      local releaseAt = orderMs + orderingDelayMs
      redis.call("ZADD", stageKey, releaseAt, jobId)
      jobStatus = "staged"
      redis.call("HSET", jobKey, "status", jobStatus)
    else
      -- Ready to process
      jobStatus = "waiting"
      redis.call("HSET", jobKey, "status", jobStatus)
      -- Mark group for ready queue update (batch later)
      groupsToUpdate[groupId] = true
    end
    
    -- Store job metadata to return
    table.insert(results, {
      jobId,
      groupId,
      data,
      "0", -- attempts
      tostring(maxAttempts),
      tostring(clientTimestamp),
      tostring(orderMs),
      "0", -- delayUntil (always 0 now)
      jobStatus,
    })
  else
    -- Job ID already exists (idempotence) - fetch existing job data
    local jobKey = ns .. ":job:" .. jobId
    local jobData = redis.call("HMGET", jobKey, "id", "groupId", "data", "attempts", "maxAttempts", "timestamp", "orderMs", "status")
    if jobData[1] then
      table.insert(results, jobData)
    else
      -- Shouldn't happen but handle gracefully
      table.insert(results, {
        jobId,
        groupId,
        data,
        "0",
        tostring(maxAttempts),
        tostring(clientTimestamp),
        tostring(orderMs),
        "0", -- delayUntil (always 0 now)
        "waiting",
      })
    end
  end
end

-- Batch update ready queue for all affected groups
for groupId, _ in pairs(groupsToUpdate) do
  local gZ = ns .. ":g:" .. groupId
  local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if head and #head >= 2 then
    local headScore = tonumber(head[2])
    redis.call("ZADD", readyKey, headScore, groupId)
  end
end

-- Update staging timer if needed
if orderingDelayMs > 0 then
  local currentHead = redis.call("ZRANGE", stageKey, 0, 0, "WITHSCORES")
  if currentHead and #currentHead >= 2 then
    local headReleaseAt = tonumber(currentHead[2])
    local ttlMs = math.max(1, headReleaseAt - now)
    redis.call("SET", timerKey, "1", "PX", ttlMs)
  end
end

return results

`,
  'enqueue-simple': `-- Simplified enqueue for non-grouped jobs
-- No group tracking, no staging, just add to simple queue
-- argv: ns, jobId, dataJson, orderMs, maxAttempts, keepCompleted, clientTimestamp
local ns = KEYS[1]
local jobId = ARGV[1]
local data = ARGV[2]
local orderMs = tonumber(ARGV[3])
local maxAttempts = tonumber(ARGV[4])
local keepCompleted = tonumber(ARGV[5]) or 0
local clientTimestamp = tonumber(ARGV[6])

local simpleKey = ns .. ":simple"
local jobKey = ns .. ":job:" .. jobId

-- Idempotence: ensure unique jobId per queue namespace
local uniqueKey = ns .. ":unique:" .. jobId
local uniqueSet = redis.call("SET", uniqueKey, jobId, "NX")
if not uniqueSet then
  -- Duplicate detected - check if job exists
  local exists = redis.call("EXISTS", jobKey)
  if exists == 0 then
    -- Stale unique key, clean up and proceed
    redis.call("DEL", uniqueKey)
    redis.call("SET", uniqueKey, jobId)
  else
    -- Job exists, return existing job data (idempotent).
    -- Read inside the script so the response is atomic with the dedup check —
    -- otherwise retention can trim the hash between this script returning and
    -- the client doing a follow-up HGETALL, causing a spurious "job not found".
    local existing = redis.call("HMGET", jobKey,
      "id", "groupId", "data", "attempts", "maxAttempts", "timestamp", "orderMs", "status")
    return {existing[1] or jobId, existing[2] or "", existing[3], existing[4] or "0",
      existing[5] or tostring(maxAttempts), existing[6] or "0",
      existing[7] or tostring(orderMs), "0", existing[8] or "waiting"}
  end
end

-- Use client timestamp or current time
local timestamp = clientTimestamp or (tonumber(redis.call("TIME")[1]) * 1000)

-- Create job hash (minimal fields for simple jobs)
redis.call("HMSET", jobKey,
  "id", jobId,
  "data", data,
  "attempts", "0",
  "maxAttempts", tostring(maxAttempts),
  "orderMs", tostring(orderMs),
  "timestamp", tostring(timestamp),
  "status", "waiting"
)

-- Add to simple queue (ZSET with score=orderMs)
redis.call("ZADD", simpleKey, orderMs, jobId)

-- Return job data
return {jobId, "", data, "0", tostring(maxAttempts), tostring(timestamp), tostring(orderMs), "0", "waiting"}
`,
  'enqueue': `-- argv: ns, groupId, dataJson, maxAttempts, orderMs, jobId, keepCompleted, clientTimestamp, orderingDelayMs
local ns = KEYS[1]
local groupId = ARGV[1]
local data = ARGV[2]
local maxAttempts = tonumber(ARGV[3])
local orderMs = tonumber(ARGV[4])
local jobId = ARGV[5]
local keepCompleted = tonumber(ARGV[6]) or 0
local clientTimestamp = tonumber(ARGV[7])
local orderingDelayMs = tonumber(ARGV[8]) or 0

local readyKey = ns .. ":ready"
local stageKey = ns .. ":stage"
local timerKey = ns .. ":stage:timer"
local jobKey = ns .. ":job:" .. jobId
local groupsKey = ns .. ":groups"

-- Idempotence: ensure unique jobId per queue namespace with stale-key recovery
local uniqueKey = ns .. ":unique:" .. jobId
local uniqueSet = redis.call("SET", uniqueKey, jobId, "NX")

-- Helper: read existing job hash and shape it like the success-path return
-- value. Done inside the Lua script (atomic with the dedup check) to avoid
-- a race where retention trims the hash between this script returning and
-- the client doing a follow-up HGETALL.
local function existingJobReply(fallbackGroupId, fallbackStatus)
  local existing = redis.call("HMGET", jobKey,
    "id", "groupId", "data", "attempts", "maxAttempts", "timestamp", "orderMs", "status")
  return {existing[1] or jobId, existing[2] or fallbackGroupId or groupId, existing[3] or data,
    existing[4] or "0", existing[5] or tostring(maxAttempts), existing[6] or "0",
    existing[7] or tostring(orderMs or 0), "0", existing[8] or fallbackStatus or "waiting"}
end

if not uniqueSet then
  -- Duplicate detected. Check for stale unique mapping
  local exists = redis.call("EXISTS", jobKey)
  if exists == 0 then
    -- Job doesn't exist but unique key does (stale), clean up and proceed
    redis.call("DEL", uniqueKey)
    redis.call("SET", uniqueKey, jobId)
  else
    -- Job exists, check its status and location
    local gid = redis.call("HGET", jobKey, "groupId")
    local inProcessing = redis.call("ZSCORE", ns .. ":processing", jobId)
    local inGroup = nil
    if gid then
      inGroup = redis.call("ZSCORE", ns .. ":g:" .. gid, jobId)
    end
    if (not inProcessing) and (not inGroup) then
      if keepCompleted == 0 then
        redis.call("DEL", jobKey)
        redis.call("DEL", uniqueKey)
        redis.call("SET", uniqueKey, jobId)
      else
        -- Job hash exists and we're keeping completed jobs, ensure unique key exists
        redis.call("SET", uniqueKey, jobId)
        return existingJobReply(gid, "completed")
      end
    else
      if keepCompleted == 0 then
        local status = redis.call("HGET", jobKey, "status")
        if status == "completed" then
          redis.call("DEL", jobKey)
          redis.call("DEL", uniqueKey)
          redis.call("SET", uniqueKey, jobId)
        else
          -- Job is still active, ensure unique key exists
          redis.call("SET", uniqueKey, jobId)
          return existingJobReply(gid, status)
        end
      end
      local activeAgain = redis.call("ZSCORE", ns .. ":processing", jobId)
      local inGroupAgain = nil
      if gid then
        inGroupAgain = redis.call("ZSCORE", ns .. ":g:" .. gid, jobId)
      end
      local jobStillExists = redis.call("EXISTS", jobKey)
      if jobStillExists == 1 and (activeAgain or inGroupAgain) then
        return existingJobReply(gid, activeAgain and "active" or "waiting")
      end
    end
  end
end

local gZ = ns .. ":g:" .. groupId

if not orderMs then
  orderMs = tonumber(redis.call("TIME")[1]) * 1000
end
local baseEpoch = 1704067200000
local relativeMs = orderMs - baseEpoch

-- Use date-based sequence key to auto-reset daily (prevents max int overflow)
local daysSinceEpoch = math.floor(orderMs / 86400000)
local seqKey = ns .. ":seq:" .. daysSinceEpoch
local seq = redis.call("INCR", seqKey)
local score = relativeMs * 1000 + seq

-- Get Redis server time for buffering logic (to be consistent with server time)
local timeResult = redis.call("TIME")
local now = tonumber(timeResult[1]) * 1000 + math.floor(tonumber(timeResult[2]) / 1000)

-- Use client timestamp for the job hash so timing calculations are accurate from client perspective
local timestamp = clientTimestamp or now

redis.call("HMSET", jobKey,
  "id", jobId,
  "groupId", groupId,
  "data", data,
  "attempts", "0",
  "maxAttempts", tostring(maxAttempts),
  "seq", tostring(seq),
  "timestamp", tostring(timestamp),
  "orderMs", tostring(orderMs),
  "score", tostring(score)
)

-- Track group membership (idempotent)
redis.call("SADD", groupsKey, groupId)

-- Determine job status and placement
local jobStatus = "waiting"

if orderMs and orderingDelayMs > 0 then
  -- Job should be staged for ordering (orderMs provided and orderingDelayMs > 0)
  -- NOTE: Do NOT add to group ZSET yet - only to staging
  local releaseAt = orderMs + orderingDelayMs
  redis.call("ZADD", stageKey, releaseAt, jobId)
  jobStatus = "staged"
  redis.call("HSET", jobKey, "status", jobStatus)
  
  -- Update/set timer to earliest staged job
  local currentHead = redis.call("ZRANGE", stageKey, 0, 0, "WITHSCORES")
  if currentHead and #currentHead >= 2 then
    local headReleaseAt = tonumber(currentHead[2])
    -- Set timer to expire when the earliest job is ready
    local ttlMs = math.max(1, headReleaseAt - now)
    redis.call("SET", timerKey, "1", "PX", ttlMs)
  end
else
  -- Job is not delayed and not staged, add to group set and make ready
  redis.call("ZADD", gZ, score, jobId)
  jobStatus = "waiting"
  redis.call("HSET", jobKey, "status", jobStatus)
  local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if head and #head >= 2 then
    local headScore = tonumber(head[2])
    redis.call("ZADD", readyKey, headScore, groupId)
  end
end

-- Return job data to avoid race condition where job might be processed & cleaned up
-- before getJob() is called
return {jobId, groupId, data, "0", tostring(maxAttempts), tostring(timestamp), tostring(orderMs), "0", jobStatus}


`,
  'get-active-count': `-- argv: ns
local ns = KEYS[1]
local processingKey = ns .. ":processing"
return redis.call("ZCARD", processingKey)


`,
  'get-active-jobs': `-- argv: ns
local ns = KEYS[1]
local processingKey = ns .. ":processing"
return redis.call("ZRANGE", processingKey, 0, -1)


`,
  'get-unique-groups-count': `-- argv: ns
local ns = KEYS[1]
local groupsKey = ns .. ":groups"
local groupIds = redis.call("SMEMBERS", groupsKey)
local count = 0
for _, groupId in ipairs(groupIds) do
  local gZ = ns .. ":g:" .. groupId
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount > 0 then
    count = count + 1
  end
end
return count`,
  'get-unique-groups': `-- argv: ns
local ns = KEYS[1]
local groupsKey = ns .. ":groups"
local groupIds = redis.call("SMEMBERS", groupsKey)
local groups = {}
for _, groupId in ipairs(groupIds) do
  local gZ = ns .. ":g:" .. groupId
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount > 0 then
    table.insert(groups, groupId)
  end
end
return groups


`,
  'get-waiting-count': `local ns = KEYS[1]
local groupsKey = ns .. ":groups"
local groupIds = redis.call("SMEMBERS", groupsKey)
local total = 0
for _, gid in ipairs(groupIds) do
  local gk = ns .. ":g:" .. gid
  total = total + (redis.call("ZCARD", gk) or 0)
end
return total


`,
  'get-waiting-jobs': `-- argv: ns
local ns = KEYS[1]
local groupsKey = ns .. ":groups"
local groupIds = redis.call("SMEMBERS", groupsKey)
local jobs = {}
for _, gid in ipairs(groupIds) do
  local gZ = ns .. ":g:" .. gid
  local groupJobs = redis.call("ZRANGE", gZ, 0, -1)
  for _, jobId in ipairs(groupJobs) do
    table.insert(jobs, jobId)
  end
end
return jobs


`,
  'heartbeat': `-- argv: ns, jobId, groupId, extendMs
local ns = KEYS[1]
local jobId = ARGV[1]
local gid = ARGV[2]
local extendMs = tonumber(ARGV[3])

-- BullMQ-style: only extend processing deadline, no group lock
local processingKey = ns .. ":processing"
local stillProcessing = redis.call("ZSCORE", processingKey, jobId)
if stillProcessing then
  local t = redis.call("TIME")
  local now = tonumber(t[1]) * 1000 + math.floor(tonumber(t[2]) / 1000)
  local newDeadline = now + extendMs
  redis.call("ZADD", processingKey, newDeadline, jobId)
  return 1
end
return 0
`,
  'is-empty': `-- argv: ns
local ns = KEYS[1]

-- Check processing jobs
local processingCount = redis.call("ZCARD", ns .. ":processing")
if processingCount > 0 then
  return 0
end

-- Check delayed jobs
local delayedCount = redis.call("ZCARD", ns .. ":delayed")
if delayedCount > 0 then
  return 0
end

-- Check simple (non-grouped) queue
local simpleCount = redis.call("ZCARD", ns .. ":simple")
if simpleCount > 0 then
  return 0
end

-- Check ready groups (jobs waiting)
local readyCount = redis.call("ZCARD", ns .. ":ready")
if readyCount > 0 then
  return 0
end


-- Check all groups for waiting jobs
local groups = redis.call("SMEMBERS", ns .. ":groups")
for _, gid in ipairs(groups) do
  local gZ = ns .. ":g:" .. gid
  local jobCount = redis.call("ZCARD", gZ)
  if jobCount > 0 then
    return 0
  end
end

-- Queue is completely empty
return 1

`,
  'promote-staged': `-- Promote staged jobs that are now ready to be processed
-- argv: ns, now, limit
local ns = KEYS[1]
local now = tonumber(ARGV[1])
local limit = tonumber(ARGV[2]) or 100

local stageKey = ns .. ":stage"
local readyKey = ns .. ":ready"
local timerKey = ns .. ":stage:timer"

local promotedCount = 0

-- Get jobs that are ready (score <= now)
local readyJobs = redis.call("ZRANGEBYSCORE", stageKey, 0, now, "LIMIT", 0, limit)

for i = 1, #readyJobs do
  local jobId = readyJobs[i]
  local jobKey = ns .. ":job:" .. jobId
  
  -- Get job metadata
  local jobData = redis.call("HMGET", jobKey, "groupId", "score", "status")
  local groupId = jobData[1]
  local score = jobData[2]
  local status = jobData[3]
  
  if groupId and score and status == "staged" then
    local gZ = ns .. ":g:" .. groupId
    
    -- Remove from staging set
    redis.call("ZREM", stageKey, jobId)
    
    -- Add to group ZSET with original score
    redis.call("ZADD", gZ, tonumber(score), jobId)
    
    -- Update job status from "staged" to "waiting"
    redis.call("HSET", jobKey, "status", "waiting")
    
    -- Check if group should be added to ready queue
    -- Add group to ready if the head job is now waiting (not delayed or staged)
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headJobId = head[1]
      local headScore = tonumber(head[2])
      local headJobKey = ns .. ":job:" .. headJobId
      local headStatus = redis.call("HGET", headJobKey, "status")
      
      -- Only add to ready if head is waiting (not delayed/staged)
      if headStatus == "waiting" then
        redis.call("ZADD", readyKey, headScore, groupId)
      end
    end
    
    promotedCount = promotedCount + 1
  end
end

-- Recompute timer: set to the next earliest staged job
local nextHead = redis.call("ZRANGE", stageKey, 0, 0, "WITHSCORES")
if nextHead and #nextHead >= 2 then
  local nextReleaseAt = tonumber(nextHead[2])
  -- Set timer to expire when the next earliest job is ready
  local ttlMs = math.max(1, nextReleaseAt - now)
  redis.call("SET", timerKey, "1", "PX", ttlMs)
else
  -- No more staged jobs, delete the timer
  redis.call("DEL", timerKey)
end

return promotedCount

`,
  'record-job-result': `-- Record job completion or failure with retention management
-- argv: ns, jobId, status ('completed' | 'failed'), timestamp, result/error (JSON), 
--       keepCompleted, keepFailed, processedOn, finishedOn, attempts, maxAttempts
local ns = KEYS[1]
local jobId = ARGV[1]
local status = ARGV[2]
local timestamp = tonumber(ARGV[3])
local resultOrError = ARGV[4]
local keepCompleted = tonumber(ARGV[5])
local keepFailed = tonumber(ARGV[6])
local processedOn = ARGV[7]
local finishedOn = ARGV[8]
local attempts = ARGV[9]
local maxAttempts = ARGV[10]

local jobKey = ns .. ":job:" .. jobId

-- Verify job exists and check current status to prevent race conditions
local currentStatus = redis.call("HGET", jobKey, "status")
if not currentStatus then
  -- Job doesn't exist, likely already cleaned up
  return 0
end

-- If job is in "waiting" state, this might be a late completion after stalled recovery
-- In this case, we should not overwrite the status or delete the job
if currentStatus == "waiting" then
  -- Job was recovered by stalled check and possibly being processed by another worker
  -- Ignore this late completion to prevent corruption
  return 0
end

if status == "completed" then
  local completedKey = ns .. ":completed"
  
  if keepCompleted > 0 then
    -- Store job metadata and add to completed set
    redis.call("HSET", jobKey, 
      "status", "completed",
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts,
      "returnvalue", resultOrError
    )
    redis.call("ZADD", completedKey, timestamp, jobId)
    -- Ensure idempotence mapping exists
    redis.call("SET", ns .. ":unique:" .. jobId, jobId)
    
    -- Trim old entries atomically
    local zcount = redis.call("ZCARD", completedKey)
    local toRemove = zcount - keepCompleted
    if toRemove > 0 then
      local oldIds = redis.call("ZRANGE", completedKey, 0, toRemove - 1)
      if #oldIds > 0 then
        redis.call("ZREMRANGEBYRANK", completedKey, 0, toRemove - 1)
        -- Batch delete old jobs and unique keys
        local keysToDelete = {}
        for i = 1, #oldIds do
          local oldId = oldIds[i]
          table.insert(keysToDelete, ns .. ":job:" .. oldId)
          table.insert(keysToDelete, ns .. ":unique:" .. oldId)
        end
        if #keysToDelete > 0 then
          redis.call("DEL", unpack(keysToDelete))
        end
      end
    end
  else
    -- keepCompleted == 0: Delete immediately (batch operation)
    redis.call("DEL", jobKey, ns .. ":unique:" .. jobId)
  end
  
elseif status == "failed" then
  local failedKey = ns .. ":failed"
  
  -- Parse error info from resultOrError JSON
  -- Expected format: {"message":"...", "name":"...", "stack":"..."}
  local errorInfo = cjson.decode(resultOrError)
  
  if keepFailed > 0 then
    -- Store failure metadata
    redis.call("HSET", jobKey,
      "status", "failed",
      "failedReason", errorInfo.message or "Error",
      "failedName", errorInfo.name or "Error",
      "stacktrace", errorInfo.stack or "",
      "processedOn", processedOn,
      "finishedOn", finishedOn,
      "attempts", attempts,
      "maxAttempts", maxAttempts
    )
    redis.call("ZADD", failedKey, timestamp, jobId)
    
    -- Note: No retention trimming for failed jobs (let clean() handle it)
  else
    -- keepFailed == 0: Delete immediately (batch operation)
    redis.call("DEL", jobKey, ns .. ":unique:" .. jobId)
  end
end

return 1

`,
  'remove': `-- argv: ns, jobId
local ns = KEYS[1]
local jobId = ARGV[1]

local jobKey = ns .. ":job:" .. jobId
local delayedKey = ns .. ":delayed"
local readyKey = ns .. ":ready"
local processingKey = ns .. ":processing"

-- If job does not exist, return 0
if redis.call("EXISTS", jobKey) == 0 then
  return 0
end

local groupId = redis.call("HGET", jobKey, "groupId")

-- Remove from delayed and processing structures
redis.call("ZREM", delayedKey, jobId)
redis.call("ZREM", processingKey, jobId)

-- Remove from completed/failed retention sets if present
redis.call("ZREM", ns .. ":completed", jobId)
redis.call("ZREM", ns .. ":failed", jobId)

-- Delete idempotence mapping
redis.call("DEL", ns .. ":unique:" .. jobId)

-- If we have a group, update group zset and ready queue accordingly
if groupId then
  local gZ = ns .. ":g:" .. groupId
  redis.call("ZREM", gZ, jobId)

  local jobCount = redis.call("ZCARD", gZ)
  if jobCount == 0 then
    redis.call("ZREM", readyKey, groupId)
    -- Clean up empty group
    redis.call("DEL", gZ)
    redis.call("SREM", ns .. ":groups", groupId)
  else
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headScore = tonumber(head[2])
      redis.call("ZADD", readyKey, headScore, groupId)
    end
  end
end

-- Finally, delete the job hash
redis.call("DEL", jobKey)

return 1


`,
  'reserve-atomic': `-- Atomic reserve operation that checks lock and reserves in one operation
-- argv: ns, nowEpochMs, vtMs, targetGroupId, allowedJobId (optional)
local ns = KEYS[1]
local now = tonumber(ARGV[1])
local vt = tonumber(ARGV[2])
local targetGroupId = ARGV[3]
local allowedJobId = ARGV[4] -- If provided, allow reserve if lock matches this job ID

local readyKey = ns .. ":ready"
local gZ = ns .. ":g:" .. targetGroupId
local groupActiveKey = ns .. ":g:" .. targetGroupId .. ":active"

-- Respect paused state
if redis.call("GET", ns .. ":paused") then
  return nil
end

-- BullMQ-style: Check if group has active jobs
local activeCount = redis.call("LLEN", groupActiveKey)

if activeCount > 0 then
  -- If allowedJobId is provided, check if it matches the active job (grace collection)
  if allowedJobId then
    local activeJobId = redis.call("LINDEX", groupActiveKey, 0)
    if activeJobId == allowedJobId then
      -- This is grace collection - we're chaining from the same job
      -- Continue to reserve next job
    else
      -- Different job is active, re-add to ready and return
      local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
      if head and #head >= 2 then
        local headScore = tonumber(head[2])
        redis.call("ZADD", readyKey, headScore, targetGroupId)
      end
      return nil
    end
  else
    -- Group has active job and this isn't grace collection, can't proceed
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headScore = tonumber(head[2])
      redis.call("ZADD", readyKey, headScore, targetGroupId)
    end
    return nil
  end
end

-- Try to get a job from the group
-- First check if head job is delayed
local head = redis.call("ZRANGE", gZ, 0, 0)
if not head or #head == 0 then
  return nil
end
local headJobId = head[1]
local jobKey = ns .. ":job:" .. headJobId

-- Skip if head job is delayed (will be promoted later)
local jobStatus = redis.call("HGET", jobKey, "status")
if jobStatus == "delayed" then
  return nil
end

-- Pop the job
local zpop = redis.call("ZPOPMIN", gZ, 1)
if not zpop or #zpop == 0 then
  -- No job available, return
  return nil
end
headJobId = zpop[1]

local job = redis.call("HMGET", jobKey, "id","groupId","data","attempts","maxAttempts","seq","timestamp","orderMs","score")
local id, groupId, payload, attempts, maxAttempts, seq, enq, orderMs, score = job[1], job[2], job[3], job[4], job[5], job[6], job[7], job[8], job[9]

-- Validate job data exists (handle corrupted/missing job hash)
if not id or id == false then
  -- Job hash is missing/corrupted, clean up if needed
  if not allowedJobId or activeCount == 0 then
    redis.call("LREM", groupActiveKey, 1, headJobId)
  end
  
  -- Re-add next job to ready queue if exists
  local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if nextHead and #nextHead >= 2 then
    local nextScore = tonumber(nextHead[2])
    redis.call("ZADD", readyKey, nextScore, targetGroupId)
  end
  
  return nil
end

-- BullMQ-style: Push to group active list if not already there (not grace collection)
if not allowedJobId or activeCount == 0 then
  -- Normal reserve: add this job to active list
  redis.call("LPUSH", groupActiveKey, id)
end
-- If this is grace collection and activeCount > 0, the active list already has the job

local deadline = now + vt

local processingKey = ns .. ":processing"
redis.call("ZADD", processingKey, deadline, id)

-- Mark job as processing for accurate stalled detection and idempotency
redis.call("HSET", jobKey, "status", "processing")

local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
if nextHead and #nextHead >= 2 then
  local nextScore = tonumber(nextHead[2])
  redis.call("ZADD", readyKey, nextScore, groupId)
end

return id .. "||GROUPMQ||" .. groupId .. "||GROUPMQ||" .. payload .. "||GROUPMQ||" .. attempts .. "||GROUPMQ||" .. maxAttempts .. "||GROUPMQ||" .. seq .. "||GROUPMQ||" .. enq .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. score .. "||GROUPMQ||" .. deadline
`,
  'reserve-batch': `-- argv: ns, nowEpochMs, vtMs, maxBatch
local ns = KEYS[1]
local now = tonumber(ARGV[1])
local vt = tonumber(ARGV[2])
local maxBatch = tonumber(ARGV[3]) or 16

local readyKey = ns .. ":ready"
local processingKey = ns .. ":processing"

-- Early exit if paused
if redis.call("GET", ns .. ":paused") then
  return {}
end

local out = {}

-- Pop up to maxBatch groups from ready set (lowest score first)
local groups = redis.call("ZRANGE", readyKey, 0, maxBatch - 1, "WITHSCORES")
if not groups or #groups == 0 then
  return {}
end

local processedGroups = {}
-- BullMQ-style: use per-group active list instead of group locks
for i = 1, #groups, 2 do
  local gid = groups[i]
  local gZ = ns .. ":g:" .. gid
  local groupActiveKey = ns .. ":g:" .. gid .. ":active"

  -- Check if group has no active jobs (BullMQ-style gating)
  local activeCount = redis.call("LLEN", groupActiveKey)
  if activeCount == 0 then
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headJobId = head[1]
      local headScore = tonumber(head[2])
      local headJobKey = ns .. ":job:" .. headJobId
      
      -- Skip if head job is delayed (will be promoted later)
      local jobStatus = redis.call("HGET", headJobKey, "status")
      if jobStatus ~= "delayed" then
        -- Pop the job and push to active list atomically
        local zpop = redis.call("ZPOPMIN", gZ, 1)
        if zpop and #zpop > 0 then
          local jobId = zpop[1]
          
          local jobKey = ns .. ":job:" .. jobId
          local job = redis.call("HMGET", jobKey, "id","groupId","data","attempts","maxAttempts","seq","timestamp","orderMs","score")
          local id, groupId, payload, attempts, maxAttempts, seq, enq, orderMs, score = job[1], job[2], job[3], job[4], job[5], job[6], job[7], job[8], job[9]

          -- Validate job data exists (handle corrupted/missing job hash)
          if not id or id == false then
            -- Job hash is missing/corrupted, skip this job and continue
            -- Re-add next job to ready queue if exists
            local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
            if nextHead and #nextHead >= 2 then
              local nextScore = tonumber(nextHead[2])
              redis.call("ZADD", readyKey, nextScore, gid)
            end
          else
            -- Push to group active list (enforces 1-per-group)
            redis.call("LPUSH", groupActiveKey, jobId)
            
            -- Mark job as processing
            redis.call("HSET", jobKey, "status", "processing")
            
            local deadline = now + vt
            redis.call("ZADD", processingKey, deadline, id)

            -- Re-add group if there is a new head job (next oldest)
            local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
            if nextHead and #nextHead >= 2 then
              local nextScore = tonumber(nextHead[2])
              redis.call("ZADD", readyKey, nextScore, gid)
            end

            table.insert(out, id .. "||GROUPMQ||" .. groupId .. "||GROUPMQ||" .. payload .. "||GROUPMQ||" .. attempts .. "||GROUPMQ||" .. maxAttempts .. "||GROUPMQ||" .. seq .. "||GROUPMQ||" .. enq .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. score .. "||GROUPMQ||" .. deadline)
            table.insert(processedGroups, gid)
          end
        end
      end
    end
  end
  -- Note: Groups with active jobs will be skipped
end

-- Remove only the groups that were actually processed from ready queue
for _, gid in ipairs(processedGroups) do
  redis.call("ZREM", readyKey, gid)
end

return out


`,
  'reserve-simple': `-- Fast reserve for non-grouped jobs
-- Just ZPOPMIN, no group locking
-- argv: ns, nowEpochMs, vtMs
local ns = KEYS[1]
local now = tonumber(ARGV[1])
local vt = tonumber(ARGV[2])

local simpleKey = ns .. ":simple"
local processingKey = ns .. ":processing"

-- Respect paused state
if redis.call("GET", ns .. ":paused") then
  return nil
end

-- Pop job from simple queue
local zpop = redis.call("ZPOPMIN", simpleKey, 1)
if not zpop or #zpop == 0 then
  return nil
end

local jobId = zpop[1]
local jobKey = ns .. ":job:" .. jobId

-- Get job data
local job = redis.call("HMGET", jobKey, "id", "data", "attempts", "maxAttempts", "orderMs", "timestamp")

if not job[1] or job[1] == false then
  -- Job hash missing/corrupted
  return nil
end

local id, payload, attempts, maxAttempts, orderMs, timestamp = job[1], job[2], job[3], job[4], job[5], job[6]

-- Mark as processing
local deadline = now + vt
redis.call("ZADD", processingKey, deadline, id)
redis.call("HSET", jobKey, "status", "processing")


-- Return format matches grouped reserve (10 fields separated by ||GROUPMQ||)
-- id, groupId (empty), data, attempts, maxAttempts, seq (0), timestamp, orderMs, score (orderMs), deadline
return id .. "||GROUPMQ||" .. "" .. "||GROUPMQ||" .. payload .. "||GROUPMQ||" .. attempts .. "||GROUPMQ||" .. maxAttempts .. "||GROUPMQ||0||GROUPMQ||" .. (timestamp or orderMs) .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. deadline
`,
  'reserve': `-- argv: ns, nowEpochMs, vtMs, scanLimit
local ns = KEYS[1]
local now = tonumber(ARGV[1])
local vt = tonumber(ARGV[2])
local scanLimit = tonumber(ARGV[3]) or 20

local readyKey = ns .. ":ready"

-- Promote delayed jobs (backoff retries) that are now due
local delayedKey = ns .. ":delayed"
local dueJobs = redis.call("ZRANGEBYSCORE", delayedKey, 0, now, "LIMIT", 0, 100)
for _, jobId in ipairs(dueJobs) do
  redis.call("ZREM", delayedKey, jobId)
  local jobKey = ns .. ":job:" .. jobId
  local gid = redis.call("HGET", jobKey, "groupId")
  if gid then
    redis.call("HSET", jobKey, "status", "waiting")
    redis.call("HDEL", jobKey, "runAt")
    local gZ = ns .. ":g:" .. gid
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headScore = tonumber(head[2])
      redis.call("ZADD", readyKey, headScore, gid)
    end
  end
end

-- Respect paused state
if redis.call("GET", ns .. ":paused") then
  return nil
end

-- Get available groups
local groups = redis.call("ZRANGE", readyKey, 0, scanLimit - 1, "WITHSCORES")

if not groups or #groups == 0 then
  return nil
end

local chosenGid = nil
local chosenIndex = nil
local headJobId = nil
local job = nil

-- Try to atomically acquire a group and its head job
-- BullMQ-style: use per-group active list instead of group locks
for i = 1, #groups, 2 do
  local gid = groups[i]
  local gZ = ns .. ":g:" .. gid
  local groupActiveKey = ns .. ":g:" .. gid .. ":active"
  
  -- Check if group has no active jobs (BullMQ-style gating)
  local activeCount = redis.call("LLEN", groupActiveKey)
  if activeCount == 0 then
    -- Check if group has jobs
    local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
    if head and #head >= 2 then
      local headJobId = head[1]
      local headJobKey = ns .. ":job:" .. headJobId
      
      -- Pop the job and push to active list atomically
      local zpop = redis.call("ZPOPMIN", gZ, 1)
      if zpop and #zpop > 0 then
        headJobId = zpop[1]
        -- Read the popped job (use headJobId to avoid races)
        headJobKey = ns .. ":job:" .. headJobId
        job = redis.call("HMGET", headJobKey, "id","groupId","data","attempts","maxAttempts","seq","timestamp","orderMs","score")
        
        -- Push to group active list (enforces 1-per-group)
        redis.call("LPUSH", groupActiveKey, headJobId)
        
        chosenGid = gid
        chosenIndex = (i + 1) / 2 - 1
        -- Mark job as processing for accurate stalled detection and idempotency
        redis.call("HSET", headJobKey, "status", "processing")
        
        -- CRITICAL: Ensure job is removed from group set (defensive check)
        -- This handles edge cases where job might still be in group set due to race conditions
        -- or if ZPOPMIN didn't fully remove it (shouldn't happen, but be safe)
        redis.call("ZREM", gZ, headJobId)
        
        break
      end
    end
  end
end

if not chosenGid or not job then
  return nil
end

local id, groupId, payload, attempts, maxAttempts, seq, enq, orderMs, score = job[1], job[2], job[3], job[4], job[5], job[6], job[7], job[8], job[9]

-- Validate job data exists (handle corrupted/missing job hash)
if not id or id == false then
  -- Job hash is missing/corrupted, clean up group active list
  local groupActiveKey = ns .. ":g:" .. chosenGid .. ":active"
  redis.call("LREM", groupActiveKey, 1, headJobId)
  
  -- Re-add next job to ready queue if exists
  local gZ = ns .. ":g:" .. chosenGid
  local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if nextHead and #nextHead >= 2 then
    local nextScore = tonumber(nextHead[2])
    redis.call("ZADD", readyKey, nextScore, chosenGid)
  end
  
  return nil
end

-- Remove the group from ready queue
redis.call("ZREMRANGEBYRANK", readyKey, chosenIndex, chosenIndex)

local deadline = now + vt

local processingKey2 = ns .. ":processing"
redis.call("ZADD", processingKey2, deadline, id)

local gZ = ns .. ":g:" .. chosenGid
local nextHead = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
if nextHead and #nextHead >= 2 then
  local nextScore = tonumber(nextHead[2])
  redis.call("ZADD", readyKey, nextScore, chosenGid)
end

return id .. "||GROUPMQ||" .. groupId .. "||GROUPMQ||" .. payload .. "||GROUPMQ||" .. attempts .. "||GROUPMQ||" .. maxAttempts .. "||GROUPMQ||" .. seq .. "||GROUPMQ||" .. enq .. "||GROUPMQ||" .. orderMs .. "||GROUPMQ||" .. score .. "||GROUPMQ||" .. deadline


`,
  'retry': `-- argv: ns, jobId, backoffMs
local ns = KEYS[1]
local jobId = ARGV[1]
local backoffMs = tonumber(ARGV[2]) or 0

local jobKey = ns .. ":job:" .. jobId
local gid = redis.call("HGET", jobKey, "groupId")
local attempts = tonumber(redis.call("HINCRBY", jobKey, "attempts", 1))
local maxAttempts = tonumber(redis.call("HGET", jobKey, "maxAttempts"))

redis.call("ZREM", ns .. ":processing", jobId)

-- BullMQ-style: Remove from group active list
local groupActiveKey = ns .. ":g:" .. gid .. ":active"
redis.call("LREM", groupActiveKey, 1, jobId)

if attempts > maxAttempts then
  return -1
end

local score = tonumber(redis.call("HGET", jobKey, "score"))
local gZ = ns .. ":g:" .. gid

-- Re-add job to group
redis.call("ZADD", gZ, score, jobId)

-- If backoffMs > 0, delay the retry
if backoffMs > 0 then
  local t = redis.call("TIME")
  local now = tonumber(t[1]) * 1000 + math.floor(tonumber(t[2]) / 1000)
  local delayUntil = now + backoffMs
  
  -- Move to delayed set
  local delayedKey = ns .. ":delayed"
  redis.call("ZADD", delayedKey, delayUntil, jobId)
  redis.call("HSET", jobKey, "runAt", tostring(delayUntil), "status", "delayed")
  
  -- Don't add to ready yet - will be added when promoted
  -- (delayed jobs block their group)
else
  -- No backoff - immediate retry
  redis.call("HSET", jobKey, "status", "waiting")
  
  -- Add group to ready queue
  local head = redis.call("ZRANGE", gZ, 0, 0, "WITHSCORES")
  if head and #head >= 2 then
    local headScore = tonumber(head[2])
    local readyKey = ns .. ":ready"
    redis.call("ZADD", readyKey, headScore, gid)
  end
end

return attempts
`,
};
